### ISSUE TITLE
See tracker in torrent details

### ISSUE THREAD

**Issue by peaveyman** [rndusr/stig#102]
When I open the details of a particular torrent is it supposed to show the tracker for that torrent in that screen?

**Comment by rndusr** [comment]
There's a separate view for that. See the `trackerlist` command, which is bound
to <t t> by default.

I didn't put that into the details because there's quite a bit of information
that is better organized in a table than in that messy details view. Also,
tracker URLs can be arbitrarily long and that doesn't integrate well into the
details layout.
