### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by mabushey** [rndusr/stig#117]
### Configuration and Scripting
`See stig help cfgman for more information.`

$ /home/michael/.local/pipx/venvs/stig/bin/stig help cfgman
help: Unknown help topic: 'cfgman'

**Comment by mabushey** [comment]
Also in that section:
`The default rc file is $XDG_CONFIG_HOME/stig/rc. XDG_CONFIG_HOME defaults to $HOME/.config if not set.`

Another error. Nope, there is no  ~/.config/stig directory. I installed via the "recommended" pipx way. The recommended way really is docker for this kind of dependency hell python mess.

**Comment by rndusr** [comment]
> help: Unknown help topic: 'cfgman'

Works for me with current master.

**Comment by rndusr** [comment]
> there is no  ~/.config/stig directory.

The configuration directory would be empty would be empty by default, so it's
not created automatically.

> The recommended way really is docker for this kind of dependency hell python mess.

It's not recommended by me, but feel free to use Docker if you prefer that.

**Comment by mabushey** [comment]
> so it's not created automatically.
Thanks for verifying this bug.

**Comment by rndusr** [comment]
stig doesn't need that directory. It works perfectly fine without it.

I don't like tools that clutter my home directory for no good reason.

That's why it is how it is. Feel free to explain how it should be and why.
Unless you convince me, I will change nothing. Snarky remarks just waste your
time and mine.

**Comment by mabushey** [comment]
@rndusr 
I apologize for coming off snarky. Stig seems pretty awesome. I don't like anything that clutters the filesystem either, I generally view apt as the correct way to install and pip as a POS. Obviously a small projects like this does not have an apt maintainer. I've never heard of pipx before, seems like a better way of handling this.

As you stated, stig does not need the config directory. The directory by default is in ~/.config which I expect applications to use. If an application creates a dir there and removes it (if empty/unmodified) on install/uninstall then I think that's completely acceptable. It would be a lot easier for a newbie to modify a blank config file, or at least find the config directory if it already exists. If you feel strongly against this, I would recommend adding a `mkdir ~/.config/stig` and `vim ~/.config/stig/rc` to the docs.

Any idea why `help cfgman` works for you but not a fresh pipx install?

**Comment by rndusr** [comment]
Apology accepted.

I've added a sentence to the README. Hope that's enough.

`help cfgman` doesn't work for you because you're using the latest release. I've
since changed the names of some help topics. The README on GitHub should always
cover how the current development version works. The README on PyPI explains the
current release: https://pypi.org/project/stig/

The markup is currently broken and I can't fix that unless I make a new
release. And I don't want to make release that says "Fix README on PyPI" in the
CHANGELOG.
