### ISSUE TITLE
Question: Why is urwidtrees 1.0.3dev is required?

### ISSUE THREAD

**Issue by doronbehar** [rndusr/stig#120]
[I'm packaging `stig` for NixOS](https://github.com/NixOS/nixpkgs/pull/67233/files/e1de8a6aaa368f5e6ab79202d31f1f93191a1096). Our version of `urwidtrees` is 1.0.2, as in [the GitHub release](https://github.com/pazz/urwidtrees/releases/tag/1.0.2). Note that [this version is not uploaded to pypi](https://pypi.org/project/urwidtrees/#history) from some reason..

In should be kind of a hassle to make our `stig` package use `urwidtrees` version `1.0.3dev` and not 1.0.2. Therefor I was wondering, what made you commit https://github.com/rndusr/stig/commit/5b62109efe13612c3f67d8f471fc00adb870cfeb ? Is it that super important in order to avoid a certain bug?

Bonus question: Are you planning on a new release anytime soon? Your last release is from almost a year ago yet development seems very active.

BTW Thanks for creating this program, it's very helpful.

**Comment by rndusr** [comment]
I think the reason was this bug in urwidtree's setup.py:
https://github.com/pazz/urwidtrees/issues/35

It was fixed on GitHub, but there is no official release with the fixed
setup.py. The urwidtrees maintainer doesn't seem very interested in packages and
releases. IIRC, the PyPI package is maintained by some urwidtrees user who also
uploaded the fixed setup.py as the 1.0.3dev version.

It's a very ugly situation and I've thought about just integrating urwidtrees
into stig. Then I would also be able to remove one or two unneeded dependencies.

Anyway: You should be able to use urwidtrees 1.0.2 without any problems as long
as that installs fine for you. I think the only different is the fixed setup.py.

----

Unfortunately, there won't be a new release soon. Development on stig has
stopped entirely for the last few months because I started another project and
then I didn't have time to work either one.

----

And thank you so much for packaging!
Feels better than any praise or thanks. :)

**Comment by doronbehar** [comment]
Oh right, cool, Thanks!
