### ISSUE TITLE
Hash not accepted as valid id

### ISSUE THREAD

**Issue by cleanhands** [rndusr/stig#128]
The transmission RPC spec uses numeric ids and hashes interchangeably. When trying to use a hash as an id stig gives the error:
>Invalid value for filter 'id'

The transmission RPC protocol specification defines ids as:
>"ids" should be one of the following:
>(1) an integer referring to a torrent id
>(2) a list of torrent id numbers, sha1 hash strings, or both
>(3) a string, "recently-active", for recently-active torrents
https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt

Implementing this would probably be as simple as changing the id validation to accept a hash since it is part of the RPC spec.

It likewise may be possible to accept "recently-active" as a valid id but the use case for this seems less obvious.

**Comment by rndusr** [comment]
How did I not know this?

Even if this wasn't supported by the RPC, I agree that this should be supported
because IDs change every time the daemon is restarted.

Thanks.

**Comment by rndusr** [comment]
Unfortunately, this doesn't work because of how filters work.

We get a list of all torrents with only the necessary fields ("id" in this case)
and compare the values of those fields with the value from the filter (e.g.
"f572d396fae9206628714fb2ce00f72e94f2258f"). The values of the "id" field is
always an integer and we never get any matches.

But I've added a "hash" filter, which is probably better anyway because it's
clearer what's expected.
