### ISSUE TITLE
add rename_append command

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/stig#129]
The rename command makes you type a whole new name to replace the whole old name. This can be annoying for torrent names with characters that are hard to type like Japanese, or for things where you just wanted to make a small change to the name. It would be nice if there was a command that would bring up a text box with the name and let you change it, then press enter to save it.
For an example, check out in the `ranger` file manager the difference between their `:rename` and `:rename_append` commands.
Another thing, not sure if it's worth a separate issue... Could there be a keybind to rename the highlighted item if I'm in the file list of a torrent?

**Comment by rndusr** [comment]
That should already be solved in current master. Pressing "f n" in the file list
opens the command line with ":rename <current file name>". You can edit the file
name and press enter to rename the file.

Similarly, "t n" in a torrent list will allow you to edit the torrent name.

I'll try to make a new release soon, but using the master branch instead of the
release should be save at the moment. The only major issue is that completion is
incomplete (ha) and not implemented for all commands. See the README for
installation instructions.

**Comment by Soundtoxin** [comment]
Thank you for clearing that up! Glad to hear it's already in. I guess I'll close this issue then.
