### ISSUE TITLE
Add a torrent, stop it automatically after fetching the files list

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#142]
Hi,

I'd like to be able to add a torrent that will be stopped as soon as the list of all the files linked to it is fetched from the network. This would be very convenient when not much disk space is available in the downloads directory, or when only one file out of many is required.

Maybe another flag to `add`?

**Comment by rndusr** [comment]
Do you mean fetching the files from a magnet URI? Because a torrent file already
contains the file list and you can add it like this: "add --stopped <file.torrent>"

If you want to download only the file list from the DHT but not any content,
that should be implemented in Transmission in my opinion. stig only has access
to a polling interface and can't reliably stop the torrent in time.

Maybe this can already be configured in Transmission's setting.json?
https://github.com/transmission/transmission/wiki/Editing-Configuration-Files

**Comment by lenormf** [comment]
Correct, I should have specified that I only use magnets.

I didn't find any option to control that behaviour in Transmission, but since the full list of files is known as soon as the torrent hits the `connected` status, I thought it would be a suitable client-side feature.

A `add -c <magnet>` flag would potentially do what I want, it's basically auto-stopping the torrent when the `connected` status is reached.

**Comment by rndusr** [comment]
But there is no guarantee that stig will ever see the "connected" status.
Transmission could download the metainfo, connect to peers and start downloading
between two polls from stig. On the first poll, Transmission says it's still
looking for the metainfo and on the next poll it says "I have downloaded 0.3 %".

This may not be common or a big deal, but it's bad design and would/should be
regarded as a bug if it happens.

Sorry, but I don't see a good way to implement this properly.

**Comment by lenormf** [comment]
Fair enough, I'll take this upstream then.

**Comment by lenormf** [comment]
https://github.com/transmission/transmission/issues/1017
