### ISSUE TITLE
Graphical glitch

### ISSUE THREAD

**Issue by Fabioah** [rndusr/stig#144]
Hi, there is a graphical glitch where the downloaded size is bigger than the effective file size.
I am using the "latest" aur package.
Tell me if I need to provide more infos. 
![far](https://user-images.githubusercontent.com/34600288/80920856-cd65a400-8d72-11ea-95f7-8eb3e7d9ebff.jpeg)

**Comment by rndusr** [comment]
It's probably not a bug. Torrent content is downloaded in small pieces. If one
of the pieces is corrupt for some reason, it is downloaded again. There may also
be another reason, e.g. Transmission could download the same piece from multiple
peers to speed things up. I can't really explain why it happens, but it happens
all the time.

Anyway, if stig shows the wrong numbers, that's because Transmission gave it the
wrong numbers and you should file a bug there.
