### ISSUE TITLE
Sort by date/age?

### ISSUE THREAD

**Issue by gotbletu** [rndusr/stig#145]
is there option to do this?

i know the original transmission-daemon-cli it was called "Sort by Age"

basically i want to see my downloads in the order it was added to the queue

**Comment by rndusr** [comment]
$ stig help sort
$ stig help bind
$ stig help keybindings

These commands should answer your question.

**Comment by gotbletu** [comment]
i read thru the help pages.
can you give me some hints or is there a default keybinding config file i can look at?


I tryed a few things, just returns **\<X\>: unknown commands**
```
vim ~/.config/stig/rc


bind --context torrent <s> <x>  sort --add !added  Sort torrents by time of addition in reverse
bind --context torrent <s> <X>  sort --add added  Sort torrents by time of addition
# bind --context filelist <s> <x>  sort --add !added  Sort torrents by time of addition in reverse
# bind --context filelist <s> <X>  sort --add added  Sort torrents by time of addition
# bind --context file <s> <x>  sort --add !added  Sort torrents by time of addition in reverse
# bind --context file <s> <X>  sort --add added  Sort torrents by time of addition
# bind --context default <s> <x>  sort --add !added  Sort torrents by time of addition in reverse
# bind --context default <s> <X>  sort --add added  Sort torrents by time of addition


```

**Comment by rndusr** [comment]
> can you give me some hints or is there a default keybinding config file i can look at?

The only "config" file is the rc file you already found, which isn't really a
config file but a list of commands that are automatically executed when you
start stig.

> bind --context torrent <s> <x>  sort --add !added  Sort torrents by time of addition in reverse

Almost.

1. bind's first positional argument is the key, but you provided the key as two
   arguments. You must quote "<s> <x>" so "sort ..." becomes the second
   positional argument. Alternatively, you can chain keys with "+": s+x

2. Similarly, you must quote the description or it is interpreted as multiple
   arguments instead of one. You also forgot the --description option in front
   of it.

3. That should work now, you may want to use the "torrentlist" context instead
   of the "torrent" context if you're pedantic. The difference is that the
   "torrent" context is active when your focus is on a torrent, so your
   keybinding wouldn't work in an empty torrent list.

**Comment by rndusr** [comment]
I've changed the default keybindings for sorting torrents and you can now press
"s m d" to sort by the time the torrent was added.

**Comment by gotbletu** [comment]
Ok thanks got it now, should put that in the examples rc for others to use
```
bind --context torrentlist --description "Sort torrents by time of addition" "s+x"  sort --add !added
bind --context torrentlist --description "Sort torrents by time of addition in reverse" "s+X"  sort --add added
```
----

> I've changed the default keybindings for sorting torrents and you can now press
> "s m d" to sort by the time the torrent was added.

This is great news then because i believe all the other torrent clients has it by default as well
