### ISSUE TITLE
Set the cursor at the end of the prompt when cycling history

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#162]
Reproducer:

- run a command from the prompt, e.g. `ls`
- open the prompt, hit the up arrow

The cursor will be at the beginning of the prompt, before "ls". It'd be more convenient if it was placed at the very end consistently.

HTH.

**Comment by rndusr** [comment]
Why would that be more convenient?

You don't have to place the cursor at the end of the command line to execute the
command.

If you want to edit the command, stig has no way to predict what you're going to
do. Placing the cursor at the end instead of keeping it somewhere in the middle may
increase travel distance for you.

Also, ctrl-e and other readline keys allow you to move the cursor very quickly.

**Comment by SeerLite** [comment]
I think, more than convenience, it's about consistency with other CLI tools and shells. Having the cursor at the beginning might be confusing (it was for me) when you're used to a workflow where it's placed at the end. `<colon><up><backspace>` is almost muscle memory for me and I'm guessing it is for other people too.

**Comment by SeerLite** [comment]
Thank you!

**Comment by rndusr** [comment]
You're welcome. :)
