### ISSUE TITLE
questions about filters, marks, keybinds

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/stig#171]
I read the help pages a bit for filters and filtersmanual, but it's still not clear to me. Can I use filter with the mark command? Is there a way to mark all stopped torrents? The best I could find was filtering to show stopped torrents in a new tab, then I could mark all torrents from there and hit ts to unstop them.
Another question, when I've hit a key and it's showing some keybinds, such as f for the tab ls commands, is it showing all of them, or is there a way to see more? Hitting tab closes it, same with down arrow. I was hoping there was a way to filter to stopped torrents, but I didn't see one in the visible binds. On that note, what's the difference between "paused" and "stopped"? I saw I could filter to paused torrents, but apparently those are different from stopped torrents. I don't think I've ever paused something. The help page for pause makes it sound the same as stop, but then why do I see nothing when filtering to paused torrents while I have one paused?
Hopefully you can clear up some of my confusion.

**Comment by Soundtoxin** [comment]
I see now that :pause makes something say it's "stopped" as well, so maybe it's a bug that the fp (tab ls paused) bind doesn't show stopped torrents.

**Comment by rndusr** [comment]
The mark command exists to allow you manually pick specific torrents that aren't
easily described by filters. If you want to do something to all stopped
torrents, you should be able to that by passing the filter "stopped" to a
command, e.g. "start stopped".

stig tries to show all the available key chains. If that's impossible, you just
can't see all of them at the moment. You can see all key bindings with "stig
help keys".

There is no difference between "paused" and "stopped". "pause" is an alias for
the "stop" command and the key binding to list stopped torrents is <f> <p>
because <f> <s> is already used for seeding torrents.

**Comment by Soundtoxin** [comment]
Thanks for the answer, but just want to clarify that in my testing, <f> <p> doesn't show my stopped torrents! It doesn't seem to show anything. Is it working on your end? The command `tab ls paused` doesn't work either, but `tab ls stopped` does work. So maybe something is broken related to what the states are called, making paused not equal to stopped.

**Comment by rndusr** [comment]
Oops. "paused" is not a filter anymore. I must've removed it as an alias during
one of my attempts to make all the names, aliases and shorthands somewhat
coherent.

You can fix this with the "bind" command.

**Comment by Soundtoxin** [comment]
>You can fix this with the "bind" command.

I actually tried this earlier with no luck.
I did `bind f+p tab ls stopped` in my rc file and still the bind seems to open the paused filter. Same if I do it with `:bind` from the running tui.

**Comment by rndusr** [comment]
You need to use the correct context. In "stig help keys" you can see that <f>
<p> is bound in the "tabs" context.
