### ISSUE TITLE
Tracker like column?

### ISSUE THREAD

**Issue by simonbcn** [rndusr/stig#18]
It can sort/filter by tracker but it can't show a column with this value.

**Comment by rndusr** [comment]
I added that yesterday.

Although it is limited to 10 characters, which is kind of ugly.  Please let me know if you have better idea.

**Comment by simonbcn** [comment]
For me it's ok now. :+1:

**Comment by peaveyman** [comment]
Can stig show this column in the active / incomplete list?

**Comment by rndusr** [comment]
Sure: `ls -c name,tracker,...`

Prepend `tab` to run the command in a new tab.

If you don't like the default tab layout, you should add your custom `tab ...`
commands to your rc file. The default tabs are only opened if you don't specify
any in the rc file or as command line arguments.

**Comment by peaveyman** [comment]
Is there a sample rc file? I'm not sure where stig looks for the rc file. I am running Manjaro, an Arch spin.

**Comment by rndusr** [comment]
`stig -h` tells you about `stig help settingsmanual` which should explain this.

`rc` stands for "run commands", meaning you can put every command from `stig
help commands` in a text file. If it's at the default `~/.config/stig/rc`, it's
loaded automatically, otherwise you have to specify it via the `--rcfile` option
or the `rc` command.
