### ISSUE TITLE
Crash when reading an invalid URL with non integer port number

### ISSUE THREAD

**Issue by doronbehar** [rndusr/stig#45]
Since the last update, I'm experiencing a crash every time I try to reach `<all>` tab. Here is [the traceback](https://gist.github.com/doronbehar/bcc71857c2864f16952d1f799375a432).

I'm confident it's not a problem with my torrents because with the previous version it doesn't happen. In addition, I couldn't find the specific torrent responsible for the bug. I ran this shell commands to make sure there is no such torrent with a tracker with such a port number:

```sh
for t in `transmission-remote -ne --list | awk '$1 ~ /[0-9]+/ {print $1}'`;do
    if transmission-remote -ne --torrent "$t" --info-trackers |\
        awk '$1 == "Tracker" && $2 ~ /[0-9]:/ && $3 ~ /udp:\/\/tracker\.coppersurfer\.tk:69692710\/announce/ { exit 0}'; then
        transmission-remote -ne --torrent "$t" --info
    fi
done
```

**Comment by rndusr** [comment]
Can you figure out which torrent causes this? And then either post the torrent
file somewhere or the tracker URL(s) from the output of `transmission-show
<torrent file>`?

**Comment by doronbehar** [comment]
That's exactly what I tried to do with the shell script posted. If I ran the same script without the port number in `awk`'s regex, I could see many torrents with this tracker and none of them had this port number, all of them were with `6969` or `80` as the port number.
Correct me if I'm wrong but I think it proves the script is good and that there is no such tracker in my torrents.

**Comment by rndusr** [comment]
Well, you don't need your script to prove that there is not tracker with a port
number of 69692710. That number is *way* too high.

The bug is probably in the URL parser. Somehow it ends up with two port numbers
concatenated. I have no idea how that happens, so I need some way to reproduce
that bug.

Don't look for the complete URL (it cannot exist), just "coppersurfer.tk". Then
pick one of the matching torrents and list that with `stig ls <name of that
torrent>`. If that doesn't thrown the exception, try the next one. Or something
like that.

Or maybe I misunderstood and you can list all torrents fine individually, just
not a complete list of all torrents in one tab? (Please don't say yes, that
would be a total mindboggler.)

**Comment by doronbehar** [comment]
Hmm that could have been a good idea but after some tests with shell loops I just realised that `stig ls` with no arguments doesn't detect the error as you expected meaning this is not the way to debug this.

**Comment by rndusr** [comment]
I meant `stig ls <name of the torrent that could trigger the bug>`. (But `stig ls` should also trigger it, since it lists all torrents.)

Does `stig tab ls` trigger the bug? What about `stig -C tab ls`?

**Comment by doronbehar** [comment]
`stig tab ls` doesn't trigger the bug as well.
`stig -C tab ls` doesn't authenticate me so I can't see anything with it but I can tell you (since `-C` is equivalent to `--no-rc-file`) that my `rc` file is as follows:
```con
# Poll every 10 seconds
set tui.poll 10

# Default columns in torrent lists
set columns.torrents name ratio rate-up rate-down

# Use a different binding for marking all torrents
unbind --context torrent 'alt-space'
bind A mark --toggle --all

set srv.url '....'
```

Perhaps I need to `set columns.torrents name ratio rate-up rate-down` when I debug it with `stig ls`?

**Comment by rndusr** [comment]
So if `stig ls` doesn't trigger the bug, you should be able to loop over all
torrent names and list each one with an individual command like this:

```sh
set -o errexit
IFS=$'\n'
for name in $(stig ls -c name); do
    echo "Trying torrent: '$name'"
    stig ls "$name"
done
```

If the bug is triggered, the loop should stop and you can see the torrent name
above the traceback.

If it doesn't trigger the bug, try messing with your settings.  Maybe add the
'tracker' column? Maybe add all columns?

> `stig -C tab ls` doesn't authenticate me

You can set the URL on the command line: `stig -C set srv.url '...' \; ls`

> Perhaps I need to `set columns.torrents name ratio rate-up rate-down` when I debug it with `stig ls`?

No, the ls command uses `columns.torrents` by default.

**Comment by doronbehar** [comment]
OK,

I ran a little bit different script:
```sh
set -e errexit
IFS=$'n'
for t in $(stig ls -c name); do
	echo "$t" > last-torrent-tried.log
	stig ls "$t"
done
```

This way, the torrent which makes the problem should appear on the file `last-torrent-tried.log`. I found out that the torrent name contains some special characters `!` and `&`. But from some reason, the bug is not triggered when I just `stig ls <part of the name of the problematic torrent without special characters>`, and when I `stig ls <The full name of the torrent>` I get a different error than reported in [the traceback](https://gist.github.com/doronbehar/bcc71857c2864f16952d1f799375a432) which is this:
```
Malformed filter expression: ' <the part of the torrent's name after the &>'
```

If it's possible, I would prefer to continue investigate the matter without indicating the magnet link or the torrent name or file which causes the error, due to privacy concerns. Unless you would like to continue using emails instead I won't mind.

Any more ideas?

**Comment by rndusr** [comment]
The 'Malformed filter expression' error is because '!' and '&' are special
characters (see `stig help filters`).

I understand your privacy concerns, but I can't debug this if I can't reproduce
it. If you find a torrent that causes this, you can send it to me via email or
any other way. Although I'm not sure how this can be done without disclosing
private information here. (Maybe with a manual Diffie-Hellman key exchange. :))

But first you have to find out which torrent causes this.

Try these:

`stig ls -c name,tracker <part of the name of the problematic torrent without special characters>`

`stig tab ls -c name,tracker <part of the name of the problematic torrent without special characters>`

Try adding more columns (`-c`).

Comment out everything in your rc file except for `set srv.url ...`.

Create torrents with the same trackers but different files and see if they
trigger the same bug.

Can't think of anything else right now.

**Comment by doronbehar** [comment]
Well first of all, I finally found the Torrent causing all the problems. It occurs only with the `tracker` column.
I won't mind sending to you an email privately with a link to the torrent or with the torrent itself. Is your public GPG key can be retrieved using `gpg --search rndusr`? It could be great if I could just send it to you and encrypt the message using the public key from the key servers..

**Comment by rndusr** [comment]
No, I don't use GPG. But it sounds like the trackers are the cause of this. Can
you post the "TRACKERS" section of the output of `transmission-show path/to/torrent`?

Or you could create a torrent with the tracker URLs slightly changed, e.g. a
different host name, confirm that this one also triggers the bug and post the
changed tracker URLs here.

**Comment by doronbehar** [comment]
The output of `transmission-remote -ne --torrent <#> --info-trackers` is [this](https://gist.github.com/dd588ba38130a3a67ee449e1f7045b43).
The output of `transmission-show /path/to/torrent` is [this](https://gist.github.com/39d7e2c6626ec8f9a386de7e1c0215f6).

I guess you can see that there are actual trackers there with very weird tracker names. I wonder how is this possible, how come the `transmission-daemon` allows it to be that way, and I wonder if this torrent is still active. I can't see there are connected peers to it..

**Comment by rndusr** [comment]
Ok, so there's actually a tracker with an invalid port number. I guess
Transmission just fails silently when trying to parse the URL but provides it to
stig when it asks for the tracker list.

It's still a bug in stig because it crashes. I should be able to fix this now.

Thanks a lot for your help!

**Comment by doronbehar** [comment]
Thank you for your guidance!

**Comment by rndusr** [comment]
I think I fixed it. Can you pull the latest master (or install/update stig-git if you're running Arch) and check if this works for you?

**Comment by doronbehar** [comment]
Yes, Fixed.

Thanks!
