### ISSUE TITLE
[Question] Line based colouring

### ISSUE THREAD

**Issue by Q3CPMA** [rndusr/stig#48]
Sorry for the lazy question, I'm still using rtorrent and only considering switching to transmission with stig. I only saw the screenshot in the README and wondered if it's possible to have more "traditional" line-based colours: everything white or gray, green for active torrents, yellow for paused, red for stopped; this kind of thing.

**Comment by rndusr** [comment]
All colors are defined in a theme file. Here's the default one:
https://github.com/rndusr/stig/blob/master/stig/settings/default.theme

It's a tedious format, but it should let you color everything how you want.

If you end up with a theme you like, feel free to share it. I'd love to ship
stig with a few different themes.

**Comment by Q3CPMA** [comment]
I see, I'll just have to duplicate a lot of stuff to get whole lines. Well, better have more than not enough choice.

**Comment by rndusr** [comment]
Yeah, sorry about that. I tried really hard to come up with a better format, but
I couldn't figure it out. Although variables can reduce the editing you have to
do by a lot. But feel free to come up with a better solution.

**Comment by Q3CPMA** [comment]
I don't think there's a better solution, if you want to be able to make it looks like a Christmas tree. Some verbosity could be a lot removed by having a default background colour (maybe foreground too?)
You'd get something like this:
before
```
$keychains_bg = black
keychains            light gray   on $keychains_bg
keychains.keys       light gray   on $keychains_bg
keychains.keys.next  yellow       on $keychains_bg
keychains.action white on $keychains_bg
```
after
```
default_background black

keychains            light gray
keychains.keys       light gray
keychains.keys.next  yellow
keychains.action white
```
You could still give a third argument to specify a different colour.

**Comment by rndusr** [comment]
Yes, most of the problems with the current format stem from the fact that the
user should be able to have a christmas tree. :) I was trying to implement some
kind of inheritance so that you can specify some or no attributes for a given
widget and it would get the missing values from the parent widget.

Your proposal makes it a little simpler, but not by much. It basically removes
the need to specify foreground and background and allows you to just specify
foreground, and that's already possible with variables.

**Comment by Q3CPMA** [comment]
Well, anyway, it'll be simple for my use case.
