### ISSUE TITLE
Add connect.url setting

### ISSUE THREAD

**Issue by oyhel** [rndusr/stig#77]
I found out by fiddling around that specifying 
set connect.host username:password@host

connected to the remote transmission server. This might be obvious to some, but you might want to add this to the docs

**Comment by rndusr** [comment]
Thanks for finding and reporting this. It's actually not intended behaviour.

stig thinks the whole `<username>:<password>@<host>` string is the host name, which is interpreted by the HTTP library, and the connection works. But If you add the port (`set connect.host <username>:<password>@<host>:9091`), it doesn't work because the port is added automatically to the host to create the full URL and you end up with `...:9091:9091`.

Another downside is that the password is displayed in the top bar.

I won't document this because it's broken for these reasons. But I agree that providing the full URL can be more convenient. Maybe `connect.url` should be re-added as a meta setting that parses the URL and set the appropriate `connect.*` settings.

**Comment by rndusr** [comment]
I've finally re-added the "connect.url" setting.

You can now "set connect.url https://foo:bar@localhost:1234/weird/path" and all connect.*
settings are kept in sync.

**Comment by apexo** [comment]
This breaks connect.user and connect.password when saving settings, because connect.url is serialized (and restored) after user/password and overwrites those.

**Comment by apexo** [comment]
I guess connect.user / connect.password should not be saved separately, but just as part of connect.url.

**Comment by rndusr** [comment]
Thanks for reporting this.

Actually, the issue was that the password was *not* part of the url and connect.url was
dump after connect.password, which removed the previously set password.

I've fixed this by including user and password in the connect.url value.

**Comment by apexo** [comment]
Awesome, thanks :)
